apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/NilkanthMiyani/terraform-aks.git
    targetRevision: main
    path: k8s-aks/helm/jerney
  destination:
    server: https://kubernetes.default.svc
    namespace: jerney
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
